### ISSUE TITLE
Travis tests frequently die, possible rate limit issue

### ISSUE THREAD

**Issue by alerque** [ickc/pancritic#13]
I was trying to see if my PRs were passing tests, and it looks like the Travis CI runs are failing semi randomly about half the time. The culprit seems to be this bit:

```yml
install: 
 - downloadUrl=$(python -c 'import requests, sys; v = sys.argv[1]; url = "https://api.github.com/repos/jgm/pandoc/releases/" + (v if v == "latest" else ("tags/" + v)); print(next(i["browser_download_url"] for i in requests.get(url).json()["assets"] if i["name"][-3:] == "deb"))' $pandocVersion) && wget $downloadUrl && sudo dpkg -i ${downloadUrl##*/}
```
Testing it locally seems to work okay.

One guess is that Github might be rate limiting unauthenticated requests to this API.

**Comment by ickc** [comment]
In the past I wrote that line using regex and thought that using GitHub API is more robust and quickly went into rate limit problem. And I guess logging in is not a solution (because people might fork) and probably I'll just revert back to regex solution.

However lately I have been experiencing some issues with Travis on another pandoc related project. I might migrate everything to Circle CI.

I restarted CI for that PR on Travis. And if you want to use the regex version of this line you can find it in history.
